### ISSUE TITLE
Open dtu wird nicht angezeigt

### ISSUE THREAD

**Issue by firehawk1979** [henne49/dbus-opendtu#160]
**Follow the Troubleshooting Section**
Change the Logging Parameter under DEFAULT in /data/dbus-opendtu/config.ini to Logging = DEBUG, please revert, once debugging and troubleshooting is complete. Rerun the script and share the current.log and config.ini file.
[Troubleshooting Section](https://github.com/henne49/dbus-opendtu#troubleshooting )

**Describe the Problem**
A clear and concise description of what the issue is.

**Device you are using**
1. Which Venus OS are you using?
2. Which Victron Device?
3. Which DTU?
4. Which Template Device?

**Expected behavior**

**Screenshots**

1 Venus OS 3.31~4
2  Cerbo GX
3 Open DTU
4 Hoymiles HMS 2000 4T

**Additional context**
2024-04-21 18:01:15,252 root CRITICAL Error at main
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/urllib3/connection.py", line 159, in _new_conn
    conn = connection.create_connection(
  File "/usr/lib/python3.8/site-packages/urllib3/util/connection.py", line 84, in create_connection
    raise err
  File "/usr/lib/python3.8/site-packages/urllib3/util/connection.py", line 74, in create_connection
    sock.connect(sa)
socket.timeout: timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/urllib3/connectionpool.py", line 665, in urlopen
    httplib_response = self._make_request(
  File "/usr/lib/python3.8/site-packages/urllib3/connectionpool.py", line 387, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/lib/python3.8/http/client.py", line 1256, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/lib/python3.8/http/client.py", line 1302, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.8/http/client.py", line 1251, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.8/http/client.py", line 1011, in _send_output
    self.send(msg)
  File "/usr/lib/python3.8/http/client.py", line 951, in send
    self.connect()
  File "/usr/lib/python3.8/site-packages/urllib3/connection.py", line 187, in connect
    conn = self._new_conn()
  File "/usr/lib/python3.8/site-packages/urllib3/connection.py", line 164, in _new_conn
    raise ConnectTimeoutError(
urllib3.exceptions.ConnectTimeoutError: (<urllib3.connection.HTTPConnection object at 0xb5bc4c70>, 'Connection to 172.168.178.51 timed out. (connect timeout=2.5)')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/usr/lib/python3.8/site-packages/urllib3/connectionpool.py", line 719, in urlopen
    retries = retries.increment(
  File "/usr/lib/python3.8/site-packages/urllib3/util/retry.py", line 436, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='172.168.178.51', port=80): Max retries exceeded with url: /api/livedata/status (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0xb5bc4c70>, 'Connecti>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/data/dbus-opendtu/dbus_service.py", line 460, in fetch_url
    json_str = requests.get(
  File "/usr/lib/python3.8/site-packages/requests/api.py", line 76, in get
    return request('get', url, params=params, **kwargs)
  File "/usr/lib/python3.8/site-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python3.8/site-packages/requests/sessions.py", line 530, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python3.8/site-packages/requests/sessions.py", line 643, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python3.8/site-packages/requests/adapters.py", line 504, in send
    raise ConnectTimeout(e, request=request)

**Comment by 0x7878** [comment]
172.168.178.51/api/livedata/status 

Is not reachable from your Cerbo device. You could login into your device and wget / curl the address and see if this works. Also your firmware is beta and probably not working. The latest release should be 3.30.

**Comment by firehawk1979** [comment]
> 172.168.178.51/api/livedata/status 
> 
> Is not reachable from your Cerbo device. You could login into your device and wget / curl the address and see if this works. Also your firmware is beta and probably not working. The latest release should be 3.30. 

Vielen Dank, habe den Fehler gefunden. Manchmal sieht man den Wald vor lauter Bäumen nicht.
