### ISSUE TITLE
Fehlermeldung mit der neuesten Version von OpenDTU

### ISSUE THREAD

**Issue by stxShadow** [henne49/dbus-opendtu#214]
**Follow the Troubleshooting Section**
Gestern habe ich meine OpenDTU nach längerer Zeit mal wieder mit einem Update versehen. Seitdem werden keine Werte mehr im VenusOS dagestellt. Folgende Fehlermeldung findet sich im current.log:

2024-08-14 11:33:15,934 root CRITICAL Error at main
Traceback (most recent call last):
  File "/data/dbus-opendtu/dbus-opendtu.py", line 109, in main
    service = DbusService(
  File "/data/dbus-opendtu/dbus_service.py", line 84, in __init__
    self.numberofinverters = self.get_number_of_inverters()
  File "/data/dbus-opendtu/dbus_service.py", line 307, in get_number_of_inverters
    meter_data = self._get_data()
  File "/data/dbus-opendtu/dbus_service.py", line 494, in _get_data
    self._refresh_data()
  File "/data/dbus-opendtu/dbus_service.py", line 384, in _refresh_data
    self.check_opendtu_data(meter_data)
  File "/data/dbus-opendtu/dbus_service.py", line 427, in check_opendtu_data
    raise ValueError("You do not have the latest OpenDTU Version to run this script,"
ValueError: You do not have the latest OpenDTU Version to run this script,please upgrade your OpenDTU to at least version 4.4.3

**Device you are using**
1. Which Venus OS are you using? -> VenusOS 3.41
2. Which Victron Device? -> Victron Cerbo
3. Which DTU? -> OpenDTU Fusion V24.8.5
4. Which Template Device? -> none

**Expected behavior**
Werte sollen weiterhin wie bisher angezeigt werden.

Danke Dir !

**Comment by stxShadow** [comment]
> Hi,
> 
> die OpenDTU scheint veraltet zu sein:
> 
> raise ValueError("You do not have the latest OpenDTU Version to run this script," ValueError: You do not have the latest OpenDTU Version to run this script,please upgrade your OpenDTU to at least version 4.4.3

Definitiv nicht. Wie ich oben geschrieben habe, passierte das nach einem Update auf 24.8.5, welches die letzte aktuelle Version ist.

Ich versuche mal ein Downgrade.

**Comment by stxShadow** [comment]
Hmmmm ... ziemlich peinlich ! Sorry, dass ich Dir Deine Zeit gestohlen habe. Nach Deiner letzten Meldung hab ich einfach nochmal alles neu installiert. Geht natürlich jetzt.

Nochmals sorry !

**Comment by stxShadow** [comment]
Ja genau. Ich habe mich an das Code Update gehalten. 

Wo ich dich gerade dran habe: ist die Abfrage einer DTU und eines Templates parallel möglich ? Hintergrund: ich habe eine OpenDTU und parallel ein paar Tasmota Devices. Derzeit laufen darum 2 Instanzen Deines Scripts. Wäre prima, wenn das nur eines sein müsste. 

Wäre nice .... ist aber vermutlich nicht möglich.

Danke wie immer für Deine unfassbar fixe Reaktion !
